name: Acceptance Tests

on:
  workflow_call

jobs:
  acceptance_tests:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install dependencies
      run: ./ci/dependencies.sh
    - name: Run autotools / configure
      run: ./autogen.sh --enable-debug
    - name: Compile and link (make)
      run: make -j8 CFLAGS="-Werror -Wall"
    - name: Run acceptance tests
      run: |
        cd tests/acceptance
        chmod -R go-w .
        ./testall --printlog --tests=common,errorlog
