name: ASAN Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  asan_unit_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install dependencies
      run: sudo apt-get install -y libssl-dev libpam0g-dev liblmdb-dev byacc curl
    - name: Run autotools / configure
      run: ./autogen.sh --enable-debug
    - name: Compile and link (make)
      run: make -j8 CFLAGS="-Werror -Wall -fsanitize=address" LDFLAGS="-fsanitize=address"
    - name: Run unit tests
      run: make -C tests/unit CFLAGS="-fsanitize=address" LDFLAGS="-fsanitize=address" check
