name: MacOS Unit Tests

on:
  workflow_call

jobs:
  macos_unit_tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install dependencies
      run: brew install lmdb automake openssl pcre2 autoconf libtool libyaml
    - name: Check tools
      run: command -v libtool && command -v automake && command -v autoconf
    - name: Check tools versions
      run: libtool -V && automake --version && autoconf --version
    - name: Run autotools / configure
      run: >
        LDFLAGS="-L`brew --prefix lmdb`/lib -L`brew --prefix openssl`/lib -L`brew --prefix pcre2`/lib"
        CPPFLAGS="-I`brew --prefix lmdb`/include -I`brew --prefix openssl`/include -I`brew --prefix pcre2`/include"
        PATH="/opt/homebrew/opt/libtool/libexec/gnubin:$PATH"
        ./autogen.sh --enable-debug
    - name: Compile and link
      run: MACOSX_DEPLOYMENT_TARGET=15.4 make -j8 CFLAGS="-Werror -Wall"
    - name: Run unit tests
      run: make -C tests/unit check
