name: MacOS Unit Tests

on:
  workflow_call

jobs:
  macos_unit_tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install dependencies
      run: brew install lmdb automake openssl@1.1 pcre
    - name: Run autotools / configure
      run: ./autogen.sh --enable-debug --with-openssl="$(brew --prefix openssl@1.1)"
    - name: Compile and link
      run: make -j8 CFLAGS="-Werror -Wall"
    - name: Run unit tests
      run: make -C tests/unit check
