name: MacOS Unit Tests

on:
  workflow_call

jobs:
  macos_unit_tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install dependencies
      run: brew install lmdb automake openssl pcre2 autoconf libtool
    - name: Run autotools / configure
      run: ./autogen.sh --enable-debug
    - name: Compile and link
      run: make -j8 CFLAGS="-Werror -Wall"
    - name: Run unit tests
      run: make -C tests/unit check
