name: Unit Tests

on:
  # run this workflow on pull_request activity
  # this includes opening and pushing more commits
  pull_request:
    branches: [ master, 3.18.x, 3.15.x ]

  # run this workflow on push/merge activity
  # pull_request activity won't detect changes
  # in the upstream branch before we merge
  push:
    branches: [ master, 3.18.x, 3.15.x ]

jobs:
  unit_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install dependencies
      run: sudo apt-get update -y && sudo apt-get install -y libssl-dev libpam0g-dev liblmdb-dev byacc curl
    - name: Run autotools / configure
      run: ./autogen.sh --enable-debug
    - name: Compile and link (make)
      run: make -j8 CFLAGS="-Wall"
    - name: Run unit tests
      run: make -C tests/unit check
